version: '3'
services:
  jenkins:
    build: .
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins
    group_add:
      - docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_GROUP=docker
      - DOCKER_GID=999
    user: root

volumes:
  jenkins_home:
    driver: local
