version: '3'
services:
  jenkins:
    build: .
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins
    group_add:
      - docker
    user: jenkins
    environment:
      - JENKINS_HOME=/var/jenkins_home

volumes:
  jenkins_home:
    driver: local
